"""create_financial_notes

Revision ID: 1af33ea2791c
Revises: 002_view
Create Date: 2026-01-28 16:32:40.896686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af33ea2791c'
down_revision: Union[str, Sequence[str], None] = '002_view'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('rcept_no', sa.String(length=14), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('report_code', sa.String(length=5), nullable=False),
    sa.Column('concept_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_ref', sa.String(length=100), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['corp_code'], ['companies.corp_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corp_code', 'rcept_no', 'concept_id', name='unique_financial_note')
    )
    op.create_index(op.f('ix_financial_notes_corp_code'), 'financial_notes', ['corp_code'], unique=False)
    op.create_index(op.f('ix_financial_notes_rcept_no'), 'financial_notes', ['rcept_no'], unique=False)
    op.alter_column('companies', 'earliest_data_year',
               existing_type=sa.INTEGER(),
               comment='Earliest year with available DART data (to avoid wasteful queries)',
               existing_comment='Earliest year with available DART data',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'earliest_data_year',
               existing_type=sa.INTEGER(),
               comment='Earliest year with available DART data',
               existing_comment='Earliest year with available DART data (to avoid wasteful queries)',
               existing_nullable=True)
    op.drop_index(op.f('ix_financial_notes_rcept_no'), table_name='financial_notes')
    op.drop_index(op.f('ix_financial_notes_corp_code'), table_name='financial_notes')
    op.drop_table('financial_notes')
    # ### end Alembic commands ###
